document.addEventListener('DOMContentLoaded', cargarSubAdmins);
async function cargarSubAdmins(){
  const tbody=document.getElementById('sa-table'); tbody.innerHTML='<tr><td colspan="4" class="empty">Cargando sub-admins...</td></tr>';
  try{ const res=await apiFetch('/api/subadmins'); if(!res.ok) throw new Error(await res.text()); const data=await res.json(); if(!data.length){tbody.innerHTML='<tr><td colspan="4" class="empty">No hay sub-admins creados</td></tr>';return;} tbody.innerHTML=data.map(sa=>`<tr><td><div class="user-row"><div class="avatar" style="background:${nextColor()}">${iniciales(sa.nombre)}</div><div><div class="user-name">${escapeHtml(sa.nombre)}</div><div class="user-email">${escapeHtml(sa.correo)}</div></div></div></td><td><span class="badge badge-purple">${escapeHtml(sa.rol||'SUB_ADMIN')}</span></td><td><span class="badge ${sa.estado==='BLOQUEADO'?'badge-red':'badge-green'}">${escapeHtml(sa.estado||'ACTIVO')}</span></td><td><div class="actions"><button class="btn btn-secondary btn-sm" onclick="cambiarEstado(${sa.id},'ACTIVO')">Activar</button><button class="btn btn-secondary btn-sm" onclick="cambiarEstado(${sa.id},'BLOQUEADO')">Bloquear</button><button class="btn btn-danger btn-sm" onclick="eliminarSubAdmin(${sa.id})">Eliminar</button></div></td></tr>`).join(''); }catch(e){console.error(e);tbody.innerHTML='<tr><td colspan="4" class="empty" style="color:#dc2626">Error al cargar sub-admins</td></tr>';}
}
async function crearSubAdmin(){
  const nombre=document.getElementById('sa-nombre').value.trim(); const rut=document.getElementById('sa-rut').value.trim(); const correo=document.getElementById('sa-email').value.trim(); const password=document.getElementById('sa-password').value.trim(); const rol=document.getElementById('sa-rol').value;
  if(!nombre||!rut||!correo){ showToast('Nombre, RUT y correo son obligatorios','⚠️'); return; }
  try{ const res=await apiFetch('/api/subadmins/crear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nombre,rut,correo,password:password||'123456',rol,estado:'ACTIVO'})}); if(!res.ok) throw new Error(await res.text()); ['sa-nombre','sa-rut','sa-email','sa-password'].forEach(id=>document.getElementById(id).value=''); showToast('Sub-Admin creado correctamente','✅'); cargarSubAdmins(); }catch(e){console.error(e);showToast('No se pudo crear el Sub-Admin','❌');}
}
async function cambiarEstado(id,estado){ try{ const res=await apiFetch(`/api/subadmins/${id}/estado?estado=${estado}`,{method:'PUT'}); if(!res.ok) throw new Error(await res.text()); showToast('Estado actualizado','✅'); cargarSubAdmins(); }catch(e){showToast('No se pudo cambiar estado','❌');} }
async function eliminarSubAdmin(id){ if(!confirm('¿Eliminar este Sub-Admin?')) return; try{ const res=await apiFetch(`/api/subadmins/${id}`,{method:'DELETE'}); if(!res.ok) throw new Error(await res.text()); showToast('Sub-Admin eliminado','🗑️'); cargarSubAdmins(); }catch(e){showToast('No se pudo eliminar','❌');} }
